[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x459b94edc35e48473b4dc47d1c10b8fde11abe31327148541b1abf59a2a65cbe'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]